<a href="https://colab.research.google.com/github/evanildo59551006-wq/notebook_exercicios_pandas_numpy/blob/main/gestao_academia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import plotly.express as px

# Projeto Integrador - Gestão da Academia
Este notebook realiza a leitura da planilha de alunos, identifica faltantes, conta alunos por turma, cria um banco de dados SQLite, gera estatísticas e gráficos.

In [5]:
# Importar bibliotecas necessárias
import pandas as pd
import sqlite3

## Leitura da Planilha
Lemos a planilha Excel com os dados dos alunos usando `pandas`.

In [6]:
from google.colab import files

uploaded = files.upload()

Saving alunos_espaco30 (1).xlsx to alunos_espaco30 (1).xlsx

In [7]:
import pandas as pd

df = pd.read_excel(
    "alunos_espaco30 (1).xlsx",
    engine="openpyxl"
)

df.head()

,Horário,Nome,Forma de Pagamento,Dia de Vencimento,Valor,Agosto,Setembro,Outubro,Novembro,Dezembro
0,6:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
import os

os.listdir()

['.config', 'alunos_espaco30 (1).xlsx', 'sample_data']

In [9]:
['/content/planilha_limpa.xlsx']

['/content/planilha_limpa.xlsx']

In [11]:
# Caminho do arquivo Excel
excel_file = "alunos_espaco30 (1).xlsx"

# Leitura da planilha
df = pd.read_excel(excel_file, engine='openpyxl')
df.head()

,Horário,Nome,Forma de Pagamento,Dia de Vencimento,Valor,Agosto,Setembro,Outubro,Novembro,Dezembro
0,6:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Limpeza de Dados
Removemos linhas onde o nome do aluno está ausente.

In [12]:
# Remover linhas sem nome
df_clean = df.dropna(subset=['Nome'])
df_clean.head()

,Horário,Nome,Forma de Pagamento,Dia de Vencimento,Valor,Agosto,Setembro,Outubro,Novembro,Dezembro
12,6:30,Eliana pix,pix,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,6:30,Ana Clapix,pix,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,6:30,Vania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,6:30,Rany,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,6:30,Jucileia pix,pix,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Identificação de Alunos Faltantes
Verificamos se o aluno não possui registro em nenhum dos meses.

In [19]:
# Verificar se o aluno está ausente em todos os meses
months = ['Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro']
df_clean['Faltante'] = df_clean[months].isnull().all(axis=1)
df_clean[['Nome', 'Horário', 'Faltante']].head()

/tmp/ipykernel_39855/2477259339.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Faltante'] = df_clean[months].isnull().all(axis=1)

            Nome Horário  Faltante
12    Eliana pix    6:30      True
13    Ana Clapix    6:30      True
14         Vania    6:30      True
15          Rany    6:30      True
16  Jucileia pix    6:30      True

## Quantidade de Alunos por Turma
Agrupamos os dados por horário para contar os alunos.

In [20]:
# Contar alunos por turma
alunos_por_turma = df_clean.groupby('Horário')['Nome'].count().reset_index()
alunos_por_turma.columns = ['Horário', 'Quantidade de Alunos']
alunos_por_turma

  Horário  Quantidade de Alunos
0   11:30                     8
1   12:30                    12
2   17:00                    12
3  17:30h                     8
4   18:00                     4
5  18:30h                    16
6   19:00                     6
7    6:30                    16
8    7:30                     4
9    8:30                     8

## Quantidade de Faltantes por Turma
Contamos os alunos faltantes por horário.

In [21]:
# Contar faltantes por turma
faltantes_por_turma = df_clean[df_clean['Faltante']].groupby('Horário')['Nome'].count().reset_index()
faltantes_por_turma.columns = ['Horário', 'Quantidade de Faltantes']
faltantes_por_turma

  Horário  Quantidade de Faltantes
0   11:30                        8
1   12:30                       12
2   17:00                       12
3  17:30h                        8
4   18:00                        4
5  18:30h                       16
6   19:00                        6
7    6:30                       16
8    7:30                        4
9    8:30                        8

## Criação do Banco de Dados SQLite
Salvamos os dados em um banco de dados SQLite.

In [22]:
from sqlalchemy import create_engine

# Create SQLite engine
engine = create_engine('sqlite:///academia.db')

In [23]:
# Importar bibliotecas necessárias
import sqlite3

# criar conexão
conexao = sqlite3.connect("banco.db")

print("Conectado com sucesso!")

Conectado com sucesso!

In [24]:
import pandas as pd
import sqlite3

In [25]:
dados = {
    "nome": ["Ana", "Carlos", "João"],
    "idade": [20, 25, 22],
    "turma": ["A", "A", "B"]
}

df_clean = pd.DataFrame(dados)

In [26]:
alunos_por_turma = df_clean.groupby("turma").size().reset_index(name="quantidade")

In [27]:
faltantes_por_turma = pd.DataFrame({
    "turma": ["A", "B"],
    "faltantes": [1, 0]
})

In [28]:
# Criar banco de dados SQLite
conn = sqlite3.connect("academia.db")

df_clean.to_sql("alunos", conn, if_exists="replace", index=False)

alunos_por_turma.to_sql(
    "estatisticas_alunos",
    conn,
    if_exists="replace",
    index=False
)

faltantes_por_turma.to_sql(
    "estatisticas_faltantes",
    conn,
    if_exists="replace",
    index=False
)

conn.commit()
conn.close()

print("Banco criado com sucesso!")

Banco criado com sucesso!

In [29]:
# Criar banco de dados SQLite
conn = sqlite3.connect("academia.db")
df_clean.to_sql("alunos", conn, if_exists="replace", index=False)
alunos_por_turma.to_sql("estatisticas_alunos", conn, if_exists="replace", index=False)
faltantes_por_turma.to_sql("estatisticas_faltantes", conn, if_exists="replace", index=False)
conn.commit()
conn.close()

In [30]:
import ipywidgets as widgets
from IPython.display import display

botao = widgets.Button(description="Clique aqui")

display(botao)

Button(description='Clique aqui', style=ButtonStyle())

In [31]:
import ipywidgets as widgets
from IPython.display import display

campo = widgets.Text(
    description='Nome:',
    placeholder='Digite um nome'
)

botao = widgets.Button(description="Pesquisar")

saida = widgets.Output()

def pesquisar(b):
    with saida:
        saida.clear_output()

        filtro = df[
            df["nome"].str.contains(
                campo.value,
                case=False,
                na=False
            )
        ]

        display(filtro)

botao.on_click(pesquisar)

display(campo, botao, saida)

Text(value='', description='Nome:', placeholder='Digite um nome')

Button(description='Pesquisar', style=ButtonStyle())

Output()

## Exportação de Arquivos
Salvamos a planilha limpa e estatísticas em arquivos separados.

In [32]:
# Exportar arquivos
df_clean.to_excel("planilha_limpa.xlsx", index=False)
alunos_por_turma.to_json("estatisticas_alunos_por_turma.json", orient="records", force_ascii=False)
faltantes_por_turma.to_json("estatisticas_faltantes_por_turma.json", orient="records", force_ascii=False)

## Visualização de Dados
Criamos gráficos para visualizar a quantidade de alunos e faltantes por turma.

In [33]:
print(alunos_por_turma.columns)

Index(['turma', 'quantidade'], dtype='object')

In [34]:
!pip install kaleido

Collecting kaleido
  Downloading kaleido-1.3.0-py3-none-any.whl.metadata (5.6 kB)
Collecting choreographer>=1.3.0 (from kaleido)
  Downloading choreographer-1.3.0-py3-none-any.whl.metadata (6.9 kB)
Collecting logistro>=1.0.8 (from kaleido)
  Downloading logistro-2.0.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: orjson>=3.10.15 in /usr/local/lib/python3.12/dist-packages (from kaleido) (3.11.8)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaleido) (26.1)
Requirement already satisfied: platformdirs>=4.3.6 in /usr/local/lib/python3.12/dist-packages (from choreographer>=1.3.0->kaleido) (4.9.6)
Requirement already satisfied: simplejson>=3.19.3 in /usr/local/lib/python3.12/dist-packages (from choreographer>=1.3.0->kaleido) (4.1.0)
Downloading kaleido-1.3.0-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.6/55.6 kB 2.6 MB/s eta 0:00:00
Downloading choreographer-1.3.0-py3-none-any.whl (52 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.6/52.6 kB 1.9 MB/s eta 0:00:00
Downloading logistro-2.0.1-py3-none-any.whl (8.6 kB)
Installing collected packages: logistro, choreographer, kaleido
Successfully installed choreographer-1.3.0 kaleido-1.3.0 logistro-2.0.1

In [35]:
print(faltantes_por_turma.columns)

Index(['turma', 'faltantes'], dtype='object')

In [36]:
faltantes_por_turma.head()

  turma  faltantes
0     A          1
1     B          0

#Cadastro de clientes

In [37]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

#Importar bibliotecas

In [38]:
import pandas as pd
import sqlite3
import ipywidgets as widgets

from IPython.display import display

#Criar banco e tabela

In [39]:
conn = sqlite3.connect("academia.db")

cursor = conn.cursor()

cursor.execute('''
CREATE TABLE IF NOT EXISTS alunos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT,
    telefone TEXT,
    forma_pagamento TEXT
)
''')

conn.commit()

#Criar campos da interface

In [40]:
campo_nome = widgets.Text(
    description='Nome:',
    placeholder='Digite o nome'
)

campo_telefone = widgets.Text(
    description='Telefone:',
    placeholder='Digite o telefone'
)

campo_pagamento = widgets.Dropdown(
    options=['PIX', 'Cartão', 'Dinheiro'],
    description='Pagamento:'
)

botao_salvar = widgets.Button(
    description='Salvar Cliente'
)

saida = widgets.Output()

#Função para salvar

In [41]:
def salvar_cliente(b):
    nome = campo_nome.value
    telefone = campo_telefone.value
    pagamento = campo_pagamento.value

    cursor.execute('''
    INSERT INTO alunos (nome, telefone, forma_pagamento)
    VALUES (?, ?, ?)
    ''', (nome, telefone, pagamento))

    conn.commit()

    with saida:
        saida.clear_output()
        print("Cliente cadastrado com sucesso!")

    campo_nome.value = ''
    campo_telefone.value = ''

#Conectar botão

In [42]:
botao_salvar.on_click(salvar_cliente)
df

,Horário,Nome,Forma de Pagamento,Dia de Vencimento,Valor,Agosto,Setembro,Outubro,Novembro,Dezembro
0,6:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,6:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
427,19:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
428,19:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429,19:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
430,19:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
431,19:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#Mostrar interface

In [43]:
import sqlite3
import pandas as pd
import ipywidgets as widgets

from IPython.display import display

In [44]:
# criar banco

conn = sqlite3.connect("academia.db")

cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS alunos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT,
    telefone TEXT,
    forma_pagamento TEXT
)
""")

conn.commit()
conn.close()

In [45]:
# campos da interface

campo_nome = widgets.Text(
    description='Nome:'
)

campo_telefone = widgets.Text(
    description='Telefone:'
)

campo_pagamento = widgets.Dropdown(
    options=['PIX', 'Cartão', 'Dinheiro'],
    description='Pagamento:'
)

botao_salvar = widgets.Button(
    description='Salvar Cliente'
)

saida = widgets.Output()

In [46]:
# função salvar

def salvar_cliente(b):

    conn = sqlite3.connect("academia.db")

    cursor = conn.cursor()

    nome = campo_nome.value
    telefone = campo_telefone.value
    pagamento = campo_pagamento.value

    cursor.execute("""
    INSERT INTO alunos (nome, telefone, forma_pagamento)
    VALUES (?, ?, ?)
    """, (nome, telefone, pagamento))

    conn.commit()
    conn.close()

    with saida:
        saida.clear_output()
        print("Cliente cadastrado com sucesso!")

    campo_nome.value = ""
    campo_telefone.value = ""

In [47]:
botao_salvar = widgets.Button(
    description='Salvar Cliente'
)

In [48]:
conn = sqlite3.connect("academia.db")

cursor = conn.cursor()

cursor.execute("PRAGMA table_info(alunos)")

print(cursor.fetchall())

conn.close()

[(0, 'nome', 'TEXT', 0, None, 0), (1, 'idade', 'INTEGER', 0, None, 0), (2, 'turma', 'TEXT', 0, None, 0)]

In [52]:
botao_salvar.on_click(salvar_cliente)

In [53]:
display(
    campo_nome,
    campo_telefone,
    campo_pagamento,
    botao_salvar,
    saida
)

Text(value='Evanildo', description='Nome:')

Text(value='618888888', description='Telefone:')

Dropdown(description='Pagamento:', options=('PIX', 'Cartão', 'Dinheiro'), value='PIX')

Button(description='Salvar Cliente', style=ButtonStyle())

Output()

In [51]:
# visualizar banco

conn = sqlite3.connect("academia.db")

df = pd.read_sql("SELECT * FROM alunos", conn)

df

     nome  idade turma
0     Ana     20     A
1  Carlos     25     A
2    João     22     B

## Conclusão
Este notebook realiza todas as etapas do projeto integrador, desde a leitura da planilha até a geração de gráficos e banco de dados.